services:
  auth_service:
    build:
      context: ./auth-service
      dockerfile: ./deploy/Dockerfile
    ports:
      - ${AUTH_APP_PORT}:${AUTH_APP_PORT}
    environment:
      PORT: ${AUTH_APP_PORT}
      APP_ENV: ${AUTH_APP_ENV}
      APP_SECRET: ${AUTH_APP_SECRET}
      PG_HOST: psql_auth
      PG_PORT: 5432
      PG_DATABASE: ${AUTH_PG_DATABASE}
      PG_USERNAME: ${AUTH_PG_USERNAME}
      PG_PASSWORD: ${AUTH_PG_PASSWORD}
      PG_SCHEMA: ${AUTH_PG_SCHEMA}
      ACCESS_TOKEN_SIGNING_KEY: ${AUTH_ACCESS_TOKEN_SIGNING_KEY}
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
    depends_on:
      psql_auth:
        condition: service_healthy
      auth_service_migrator:
        condition: service_completed_successfully
  psql_auth:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_PG_DATABASE}
      POSTGRES_USER: ${AUTH_PG_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_PG_PASSWORD}
    ports:
      - ${AUTH_PG_PORT}:5432
    volumes:
      - psql_auth_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_PG_USERNAME} -d ${AUTH_PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  auth_service_migrator:
    build:
      context: ./auth-service
      dockerfile: ./deploy/Dockerfile.migrator
    environment:
      PORT: ${AUTH_APP_PORT}
      APP_ENV: ${AUTH_APP_ENV}
      APP_SECRET: ${AUTH_APP_SECRET}
      PG_HOST: psql_auth
      PG_PORT: 5432
      PG_DATABASE: ${AUTH_PG_DATABASE}
      PG_USERNAME: ${AUTH_PG_USERNAME}
      PG_PASSWORD: ${AUTH_PG_PASSWORD}
      PG_SCHEMA: ${AUTH_PG_SCHEMA}
      ACCESS_TOKEN_SIGNING_KEY: ${AUTH_ACCESS_TOKEN_SIGNING_KEY}
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
    restart: no
    depends_on:
      psql_auth:
        condition: service_healthy
volumes:
  psql_auth_data:
