app:
  name: "auth-service"
  version: "1.0.0"
  app_env: "development"

http:
  port: "8080"
  cors_allow_origins: "http://localhost:5173"

logger:
  log_level: "debug"

postgres:
  pool_max: 10

access_token:
  ttl: 24h
  cookie_key: "access_token"
